# enrollment-agents tuple layer.
D = {
"00": [
 ("route valid but ambiguous", "hold in clarification queue; never route on 'most likely'"),
 ("signature invalid on authority intent", "reject + integrity.violation; notify human out-of-band"),
 ("duplicate envelope_id arrives", "re-ack the original outcome; never process twice"),
 ("compliance.hold received mid-run", "suspend the named family's traffic; only 12's release or human direction resumes it"),
 ("a spoke reports done without its artifact", "treat as not-done; the artifact is the proof"),
 ('authority intent arrives with no registered signer for that lane', 'reject fail-closed + integrity.violation; an unregistered authority lane does not exist'),
 ("an agent's wait on another passes its timeout", 'agent.status to 14; waits are visible by rule, never discovered by surprise'),
],
"01": [
 ("family volunteers sensitive child information", "capture only the operational need, route the rest to human; minimization is the rule"),
 ("same family inquires through two channels", "one deduplicated record; identical process either way"),
 ("family asks about accommodations", "route to human immediately; accommodation conversations are never automated"),
 ("inquiry references another family's situation", "the other family's data never enters this record; cross-family references route to human"),
 ('safeguarding language or observation appears at intake', 'safeguarding.notice verbatim same turn to human, 13, 14; no follow-up questions, no statements - the words go to the human untouched'),
 ('caller states a custody or authorization change', 'custody.notice to 02, 10, 13 with the statement verbatim; nothing about the record changes until verified documentation and human approval'),
],
"02": [
 ("two applications compete for one seat", "both packages in receipt order with timestamps; the swarm ranks nothing"),
 ("family asks why they were not admitted", "route verbatim; decision communication is the human's, never templated"),
 ("application complete except a document in transit", "package goes with the gap named; no silent holds"),
 ("a referral source asks about an application's status", "nothing discloses; family-authorized channels only"),
 ('custody.notice lands on an active family', 'pipeline posture re-anchored; any pending offer, release, or disclosure re-checks against the noticed change before it moves'),
 ('jurisdiction.change.notice affects admissions requirements', 'requirements re-derived forward; families already in process are re-checked, never retroactively failed without human review'),
 ('family.optout received', 'marketing and nudge lanes halt; enrollment-obligation messages continue and are named as such'),
],
"03": [
 ("immunization record present but adequacy unclear", "present-unreviewed, route to the licensed human; the swarm never reads the shots"),
 ("custody order arrives", "presence recorded, content sealed, human notified; its terms apply only by human reading"),
 ("prior school claims records were sent, nothing arrived", "both facts recorded; absence with the claim attached is the status"),
 ("an exemption request arrives", "route verbatim; grant/deny is a human decision"),
 ('jurisdiction.change.notice alters verification requirements', 'the requirement set re-derives from the cited source; in-flight verifications re-check - the earlier/stricter requirement wins'),
],
"04": [
 ("reply contains a child wellbeing or safety concern", "route to human immediately and verbatim; safety content never waits in a queue"),
 ("template merge would reveal another family's information", "hold; cross-family data in a send is the named failure"),
 ("family requests another language", "route to human for the approved-translation decision"),
 ("family requests contact stop", "honor per rule; only human-directed required notices may still send"),
 ('safeguarding language appears in any family message', "safeguarding.notice verbatim same turn; the service conversation neither references it nor stops conspicuously - what happens next is the human's call alone"),
 ('family requests no contact', 'family.optout to 02, 07, 13; one confirmation, then the named lanes go silent; enrollment obligations continue and say so'),
 ('custody change stated in the family channel', 'custody.notice verbatim; the swarm never adjudicates custody - documentation and human approval move the record'),
],
"05": [
 ("document type unidentifiable without reading", "type-unknown, route to human; identification never excuses reading"),
 ("document arrives for the wrong child", "misdirect protocol: human immediately, incident logged"),
 ("required form missing at an enrollment gate", "the gate holds with the gap named; readiness is a fact"),
 ("a form arrives partially completed", "received-defective, re-request once with the defect named"),
 ('court order or custody documentation received', 'custody.notice to 02, 10, 13 with existence/type/date/source; content handling per sealed rules - interpretation is human territory'),
],
"06": [
 ("family requests a private tour outside the calendar", "route to human; calendar exceptions are human decisions applied identically"),
 ("tour no-show asks to rebook repeatedly", "the published rebooking rule governs; the rule is the boundary"),
 ("staff share impressions after a tour", "not recorded here; the tour record carries attendance facts only"),
 ("a tour request names a specific classroom to observe", "the published tour format governs; format exceptions are human decisions"),
 ('safeguarding concern observed around a tour or event', 'safeguarding.notice verbatim same turn; the event record stays factual and separate'),
],
"07": [
 ("two entries tie under priority rules", "the ratified tiebreak (application timestamp) decides; never ad-hoc"),
 ("family claims a different position than the record", "the record's order stands; the claim routes with the rule math attached"),
 ("human asks to move a family up", "record and route as a policy exception; if directed, recorded with its authority - never silent"),
 ("an offer window expires during a family emergency", "the expiry fact routes to human before the next offer fires; the rule pauses on a human decision only"),
 ('family.optout received on a waitlisted family', 'nudges halt; the waitlist entry itself stands until the family says otherwise - an opt-out is not a withdrawal'),
],
"08": [
 ("human terms differ from the published tuition schedule", "route back named; a nonstandard rate is a signed exception, never a quiet merge"),
 ("executed agreement returns with a handwritten change", "record as-executed, flag the delta; the record carries what was signed"),
 ("immunization gate open at the start date", "hold and escalate with the compliance clock; the gate is statutory in most jurisdictions"),
 ("an enrollment is requested that 11's capacity facts cannot seat", "the capacity fact governs; the conflict routes - the ratio has no override"),
],
"09": [
 ("family disputes a charge", "both readings preserved; the ledger reports, the human resolves"),
 ("payment arrives for a withdrawn student", "record unapplied and route; a closed ledger never silently reopens"),
 ("delinquency reaches the published exclusion threshold", "facts route to human; a child's attendance is never cut off by automation"),
 ("a signed discount references terms that changed since signing", "hold and re-confirm naming both states"),
 ('tuition books do not reconcile to the penny', "reconciliation.exception to human and 13 - $0.00 tolerance (ratified 2026-07-18); 'close enough' is the named breach"),
 ('withdrawal refund contemplated', 'computed from the published schedule and shown; execution only on signed refund.authority - refunds are money, same doctrine as discounts'),
],
"10": [
 ("receiving school requests records directly", "recorded and routed; nothing releases without authorization on file and the human's act"),
 ("withdrawal mid-billing-cycle", "proration facts per published policy; the refund decision is the human's"),
 ("custody-conflicted instructions arrive", "freeze and route to human immediately; custody conflicts are legal territory"),
 ("a release authorization is ambiguous in scope", "both readings route; a records release never proceeds on a guessed scope"),
 ('custody.notice on a family in withdrawal/transfer', 'release and records posture re-anchored; no release proceeds against a noticed change without human approval - the noticed change freezes the ambiguity, not the family'),
],
"11": [
 ("a directed enrollment would exceed the licensed ratio", "refuse + integrity.violation; the ratio has no override - the safety ceiling in a classroom"),
 ("a staffing change alters the effective ratio mid-day", "capacity recomputes immediately; the change routes to human - ratios are live math"),
 ("roster and enrollment records disagree", "both facts to human; the roster never silently reconciles"),
 ("a capacity fact would open a seat for under the offer-window duration", "the fact routes with the window math; a seat that cannot survive the published window is a human call"),
 ('jurisdiction.change.notice alters ratios or capacity rules', 'the math re-derives from the cited source; if current enrollment exceeds the new line, human immediately with the numbers - the cap is law, the remedy is human'),
],
"12": [
 ("state and local rules differ on an immunization window", "the shorter protection governs; the conflict escalates for the table"),
 ("an enrollment date is disputed", "the earlier date runs the clocks; conservatism ratified"),
 ("a certain miss emerges", "escalate immediately, quantified; early certainty is compliance"),
 ("a rule change is announced but not ratified into the table", "alert with the delta; the table changes only by ratification"),
 ('licensing or regulatory change lands', 'jurisdiction.change.notice to 02, 03, 11, 13 with source and effective date; conservatism rule - the stricter requirement and earlier date govern'),
 ('records.disclosure.package pending past lead-time', 'deadline.alert; a records-response clock is a clock like any other'),
],
"13": [
 ("two entries conflict on a material fact", "both stand; conflict flagged to the requester"),
 ("a request would unseal medical or custody content", "refuse with the seal named"),
 ("retention conflicts with an open dispute or licensing matter", "the hold wins; escalate"),
 ("storage write unconfirmed", "not done until re-verified; unconfirmed is reported failed"),
 ('external records request arrives (agency, school, parent)', 'assemble the disclosure inventory - existence, type, date, source only, custody flags named per item - records.disclosure.package to human and 12; release is a human decision, always custody-checked'),
 ('safeguarding.notice received', 'recorded verbatim with sealed handling; access to this record is itself logged'),
],
"14": [
 ("book source unavailable at assembly", "section marked absent; never backfilled"),
 ("EOD sweep finds an untouched morning item", "miss named with its owner; the sweep never reassigns"),
 ("human unreachable at book time", "publish to the queue and hold"),
 ("a ratio-margin flag spans the book boundary", "it leads both books until resolved; ratio state never ages into a footnote"),
 ('agent.status reports a wait past threshold', 'named in report.package with age and blocking party; the morning report carries every wait'),
 ('safeguarding.notice received', 'ops visibility same turn; the record shows the handoff happened - nothing else about it appears in routine reporting'),
],
}
